CREATE TABLE CONTATO(
ID_CONTATO  INTEGER NOT NULL,
NOME        VARCHAR(100) NOT NULL,
TELEFONE    VARCHAR(15) NOT NULL,
CELULAR     VARCHAR(15) NOT NULL,
EMAIL       VARCHAR(100) NOT NULL,
CONSTRAINT PK_ID_CONTATO PRIMARY KEY(ID_CONTATO));